AllCops:
  TargetRubyVersion: 2.3

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/AccessorMethodName:
  Enabled: false

Metrics/LineLength:
  Max: 100
Documentation:
  Enabled: true

MethodLength:
  Max: 12